name: Universal Core
description: Access to Basic Information is a Human Right.
meta_description: >
    The worlds best information available for free for every
    human being on the planet with a cell phone.

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /unicore

# Details for the RSS feed generator
url:            'http://praekelt.github.io/unicore/'
author:         'Praekelt Foundation'
